### PR TITLE
Create sum of array.c

### PR DESCRIPTION
**Pull request by Azmeerabhagyasree**
sum of array by azmeera bhagya sree
done the sum of arrays using function which is a easy process  
Screenshot (304)

### CODE REVIEW

**Review by its-Kumar — COMMENTED** [review]
If you are defining the summation function above the main function then why you are declared this in line 2. You can remove this line

**Comment by its-Kumar** [comment]
Also please format you code and use proper indentation

**Comment by Azmeerabhagyasree** [comment]
ok i will remove the line 2  
then anything else need to do

**Review by its-Kumar — COMMENTED** [review]
You need to write clean code.
Your code is looking very bad, no proper indentation.

**Pull request closed without merging**
