### PR TITLE
Added Queue

### PR DESCRIPTION
**Pull request by ajaylather**
Added Queue

### CODE REVIEW

**Review by its-Kumar — CHANGES_REQUESTED** [review]
Please check your commit before sending PR

**Review by ajaylather — COMMENTED** [review]
That looked like an issue from the VS Code side..nevermind, updated the code now

**Comment by its-Kumar** [comment]
> That looked like an issue from the VS Code side..nevermind, updated the code now

You need to use git commandline for better use of git

**Comment by ajaylather** [comment]
Well, I did use the command line only assuming that if git status is showing updates to a new file then the changes are already included. So, committed my changes and created a PR.

**Comment by its-Kumar** [comment]
No you have to accept change every time by using `git add` command

**Comment by ajaylather** [comment]
As a standard two-step practice, already done git add before committing. The issue was with VS Code. Tried editing the file later on and it didn't show the changes on the git repo. Restarting VS Code worked.

**Pull request closed without merging**
