### PR TITLE
Added Djikstra's Algorithm

### PR DESCRIPTION
**Pull request by anandamideShakyan**
Please take a look at my PR. 
Thank You :)

### CODE REVIEW

**Comment by its-Kumar** [comment]
> Please take a look at my PR. Thank You :)

Hey! This file seems empty 😸

**Comment by anandamideShakyan** [comment]
> > Please take a look at my PR. Thank You :)
> 
> Hey! This file seems empty 😸

Fixed :)

**Comment by its-Kumar** [comment]
Ok

**Comment by its-Kumar** [comment]
@anandamideShakyan is this complete algorithms and code is running fine or not ??

**Comment by anandamideShakyan** [comment]
> @anandamideShakyan is this complete algorithms and code is running fine or not ??

Yes, it is running fine on my system.
Is there any issue?

**Comment by its-Kumar** [comment]
Ok I'm merging

**Pull request merged**
